name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    name: Docs
    uses: fomoweth/github-workflows/.github/workflows/foundry-docs.yml@feat/foundry-docs
