name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  foundry-ci:
    name: Foundry CI
    uses: fomoweth/github-workflows/.github/workflows/foundry-ci.yml@feat/foundry-ci
    with:
      foundry-profile: ci
